package com.company.myapp.enums;

public enum JSONValidatorCode {
	VALID,
	INVALID_JSON,
	INVALID_NUMBER,
	INVALID_FIRST_NAME,
	INVALID_LAST_NAME,
	INVALID_PHONE_NUMBER,
	INVALID_PICTURE,
	INVALID_ACTIVE_VALUE,
	INVALID_FROM_CITY,
	INVALID_FROM_ZIP,
	INVALID_TO_CITY,
	INVALID_TO_ZIP,
	INVALID_DATE,
	INVALID_TIME,
	INVALID_MAKE,
	INVALID_MODEL,
	INVALID_COLOR,
	INVALID_PLATE_STATE,
	INVALID_PLATE_SERIAL,
	INVALID_MAX_PASSENGERS,
	INVALID_AMMOUNT_PER_PERSON,
	INVALID_CONDITIONS
}
